### ISSUE TITLE
Projecting to a Different Type - Error Calling Function on Result

### ISSUE THREAD

**Issue by jdfrank** [ElasticLINQ/ElasticLINQ#109] opened 2017-02-23 19:17 UTC
I created a trivial class called WebUserSummary that contains only three fields: Id, Forename, and Surname. I then project  some Webuser objects over to WebSummaries. This works thanks to a recent fix. I can call OrderBy on the result and this works. When I try to call ToList after the OrderBy, however, I receive an exception.           

```csharp
var wu = ctx.Query<WebUser>().Where(x => x.Forename == "Emily")
        .Select(x => new WebUserSummary
            {
                Id = x.Id,
                Forename = x.Forename,
                Surname = x.Surname
            }).OrderBy(x => x.Forename).ToList();
```
Expression of type 'System.Linq.IQueryable`1[ElasticLinq.IntegrationTest.Models.WebUser]' cannot be used for parameter of type 'System.Linq.IQueryable`1[ElasticLinq.IntegrationTest.Models.WebUserSummary]' of method 'System.Linq.IOrderedQueryable`1[ElasticLinq.IntegrationTest.Models.WebUserSummary] OrderBy[WebUserSummary,String](System.Linq.IQueryable`1[ElasticLinq.IntegrationTest.Models.WebUserSummary], System.Linq.Expressions.Expression`1[System.Func`2[ElasticLinq.IntegrationTest.Models.WebUserSummary,System.String]])'

**Comment by damieng** [comment] 2017-02-23 19:47
This is caused by the OrderBy being after the projection.  If you move it before the .Select does it work?

**Comment by jdfrank** [comment] 2017-02-24 20:47
Reordering the calls fixes the example code I posted, but does not work in my actual code. After the ordering, we use an extension method to convert the IQueryable into a custom class. This continues to error regardless of the call order. 

Can you give me an estimate of difficulty of a potential fix? We have been looking at the code, but there is a some learning curve there.

Thanks in advance for any response.

**Comment by damieng** [comment] 2017-02-24 20:52
This isn't a fix as such - You're ordering by a different class to the one represented by the database - i.e. after transformation.  A lot of LINQ providers don't follow the flow of properties through such transformations - EF 4.0 did not for example although LINQ to SQL did.  Following such transformations is a non-trivial amount of work that as you can see is quite easily avoided in the simple case.

What error are you getting out of your transform with the orderby moved?

**Comment by jdfrank** [comment] 2017-02-24 21:07
I put our custom collection class in the ElasticLINQ project to recreate the error. It's basically the same error as above. 

Expression of type 'System.Linq.IOrderedQueryable`1[ElasticLinq.IntegrationTest.Models.WebUser]' cannot be used for parameter of type 'System.Linq.IQueryable`1[ElasticLinq.IntegrationTest.Models.WebUserSummary]' of method 'System.Linq.IQueryable`1[ElasticLinq.IntegrationTest.Models.WebUserSummary] Skip[WebUserSummary](System.Linq.IQueryable`1[ElasticLinq.IntegrationTest.Models.WebUserSummary], Int32)'

Thanks for all the attention.

**Comment by damieng** [comment] 2017-02-25 03:03
What does the method look like?

**Comment by jdfrank** [comment] 2017-02-27 18:54
I boiled it down quite a bit. This snippet recreates the error:

```csharp
var wu = ctx.Query<WebUser>().Where(x => x.Forename == "Emily")
   .OrderBy(x => x.Forename)
   .Select(x => new WebUserSummary {
	Id = x.Id,
	Forename = x.Forename,
	Surname = x.Surname
      })
   .Skip(1).Take(1).ToList();
```
If I simply call .ToList() without the skip and take calls, it works fine. 

Thanks again.

**Comment by damieng** [comment] 2017-02-27 19:00
If you move the Skip and Take before the Select does it work?

Basically the Select needs to be the last part of the LINQ chain in ElasticLINQ here - because the Select is creating a new class altogether the Skip/Take are not considered as part of the Query&lt;WebUser>

**Comment by damieng** [comment] 2017-03-30 02:06
Not had any response on this in a month so closing the issue. Feel free to continue to respond if you need to and I'll re-open as appropriate.

**Closed as completed by damieng** 2017-03-30 02:06 UTC
